name: Spark Pipeline CI

on:
  push:
    branches: [ main ]

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Buil
      d Docker image
        run: docker build -t spark-pipeline .

      - name: Run tests
        run: docker run --rm spark-pipeline pytest /app/test/test_pipeline.py